********************************************************************************
* SIZE PROFILE  —  threshold existence (not location) + plateau
********************************************************************************
* Input : Data\release_shocks.csv, Data\macro_shock.dta, Data\tail_shock.dta,
*         Data\monetary_policy_induced_position.csv
* Output: Data\pooled_shock.dta + existence tests robust to the small-shock
*         cutoff + plateau flatness + policy-type premium.
*
* Design note: the activation threshold is generated by margin buffers and
* transaction costs, which vary across funds, bonds and time. Heterogeneous
* thresholds imply the AGGREGATE profile has no estimable kink - amplification
* rises smoothly from zero and flattens once most positions are activated. We
* therefore test EXISTENCE, not location: for every reasonable cutoff c,
* amplification per bp on small-shock days (|S| <= c) is (a) indistinguishable
* from zero and (b) significantly BELOW the plateau level (|S| > c). Under the
* no-threshold alternative (pure proportionality) the two slopes are equal -
* that is the null being rejected. The pooled series S is a decomposition of
* the daily 2y OIS change into identified components (release-fitted, policy,
* unscheduled tail); identification is established per component in the
* respective sections, the pooled regressions only aggregate.
* Run sections top-to-bottom.
********************************************************************************

clear all

********************************************************************************
* 1. Pooled daily shock series (decomposition of the daily 2y OIS change)
********************************************************************************

import delimited "C:\\Users\\hermesf\\Projects\\JobMarket\\Data\\release_shocks.csv", clear
keep date d_ois2y_bp ecb_day n_releases
rename date business_date
merge 1:1 business_date using "C:\\Users\\hermesf\\Projects\\JobMarket\\Data\\macro_shock.dta", keep(master match) nogen
merge 1:1 business_date using "C:\\Users\\hermesf\\Projects\\JobMarket\\Data\\tail_shock.dta", keep(master match) nogen

gen double S = 0
replace S = S + macro_shock if !missing(macro_shock)     // release-explained news
replace S = S + tail_shock  if !missing(tail_shock)      // unscheduled tail news
replace S = d_ois2y_bp      if ecb_day == 1              // MP events, daily basis

gen byte policy_day = (ecb_day == 1)
gen double rel_shock = cond(missing(macro_shock), 0, macro_shock)   // day-type tags
gen double tl_shock  = cond(missing(tail_shock),  0, tail_shock)    // for Section 6
keep business_date S policy_day rel_shock tl_shock
save "C:\\Users\\hermesf\\Projects\\JobMarket\\Data\\pooled_shock.dta", replace

********************************************************************************
* 2. Threshold existence, robust to the small-shock cutoff
********************************************************************************

import delimited "C:\\Users\\hermesf\\Projects\\JobMarket\\Data\\monetary_policy_induced_position.csv", clear
merge m:1 business_date using "C:\\Users\\hermesf\\Projects\\JobMarket\\Data\\pooled_shock.dta", keep(match) nogen

encode collateral_country, gen(col_cntr)
gen duration_bin = floor(duration / 2) * 2
gen duration_match = string(duration_bin) + "_" + business_date + "_" + collateral_country
gen log_hf_intensity = log(1 + hf_intensity_pre)

* two-slope specification per cutoff c: report (a) beta_small = 0 and
* (b) beta_small = beta_large for every c - existence without location
foreach c of numlist 0.5 0.75 1 1.5 2 {
    gen double hfd_small = log_hf_intensity * (abs(S) <= `c' & S != 0)
    gen double hfd_large = log_hf_intensity * (abs(S) >  `c')
    gen double hfS_small = log_hf_intensity * S * (abs(S) <= `c')
    gen double hfS_large = log_hf_intensity * S * (abs(S) >  `c')

    di as text _n "================ cutoff c = `c' bp ================"
    reghdfe delta_y c.log_hf_intensity hfd_small hfd_large hfS_small hfS_large ///
        duration bid_ask_spread ctd_flag, absorb(duration_match isin) ///
        vce(cluster business_date isin)
    test hfS_small == 0                    // (a) dead zone: zero amplification
    test hfS_small == hfS_large            // (b) below the plateau (existence)

    drop hfd_small hfd_large hfS_small hfS_large
}

********************************************************************************
* 3. Plateau: flatness above the (unpinned) threshold region
********************************************************************************
* Conditional on |S| > 1bp (representative cutoff; Section 2 shows results do
* not hinge on it): convexity term tests whether the per-bp amplification
* rises with size within the plateau. hfS_size = 0 -> flat share.

gen double hfd_large = log_hf_intensity * (abs(S) > 1)
gen double hfS_large = log_hf_intensity * S * (abs(S) > 1)
gen double hfS_size  = log_hf_intensity * S * abs(S) * (abs(S) > 1)

reghdfe delta_y c.log_hf_intensity hfd_large hfS_large hfS_size ///
    duration bid_ask_spread ctd_flag, absorb(duration_match isin) ///
    vce(cluster business_date isin)
test hfS_size == 0

********************************************************************************
* 4. Type premium within the same specification (policy vs news/risk days)
********************************************************************************

gen double hfd_policy = log_hf_intensity * policy_day
gen double hfS_policy = log_hf_intensity * S * policy_day

reghdfe delta_y c.log_hf_intensity hfd_large hfd_policy hfS_large hfS_policy ///
    duration bid_ask_spread ctd_flag, absorb(duration_match isin) ///
    vce(cluster business_date isin)
test hfS_policy == 0                       // policy premium over news/risk

********************************************************************************
* 5. Robustness: intraday EA-MPD measurement on ECB days
********************************************************************************

gen double S_intra = S
replace S_intra = ois_2y if policy_day == 1
gen double hfd_small_i = log_hf_intensity * (abs(S_intra) <= 1 & S_intra != 0)
gen double hfd_large_i = log_hf_intensity * (abs(S_intra) > 1)
gen double hfS_small_i = log_hf_intensity * S_intra * (abs(S_intra) <= 1)
gen double hfS_large_i = log_hf_intensity * S_intra * (abs(S_intra) > 1)

reghdfe delta_y c.log_hf_intensity hfd_small_i hfd_large_i hfS_small_i hfS_large_i ///
    duration bid_ask_spread ctd_flag, absorb(duration_match isin) ///
    vce(cluster business_date isin)
test hfS_small_i == hfS_large_i

********************************************************************************
* 6. Is the policy premium a directionality-composition effect?
********************************************************************************
* Hypothesis: funds run directional duration books INTO ECB meetings, so the
* type premium in Section 4 could reflect the book on the field rather than
* the shock's content. holder_dir_pre replicates directionality.do (5-day
* trailing mean over prior active days; 0 for no-HF bonds = baseline).
* Runnable directly after Section 2 (regenerates what it needs).

foreach v in isin_id hd_sum hd_cnt hd_pre hd day_type {
    capture drop `v'
}
encode isin, gen(isin_id)
sort isin_id business_date
by isin_id: gen double hd_sum = 0
by isin_id: gen double hd_cnt = 0
forvalues k = 1/5 {
    by isin_id: replace hd_sum = hd_sum + holder_dir[_n-`k'] ///
        if _n > `k' & !missing(holder_dir[_n-`k'])
    by isin_id: replace hd_cnt = hd_cnt + 1 ///
        if _n > `k' & !missing(holder_dir[_n-`k'])
}
gen double hd_pre = hd_sum / hd_cnt if hd_cnt > 0
gen double hd = cond(missing(hd_pre), 0, hd_pre)

* 6.1 descriptive: is pre-event directionality higher on policy days?
gen day_type = 0
replace day_type = 1 if rel_shock != 0
replace day_type = 2 if tl_shock != 0 & abs(tl_shock) > abs(rel_shock)
replace day_type = 3 if policy_day == 1
label define daytype 0 "quiet" 1 "release" 2 "tail" 3 "policy", replace
label values day_type daytype
tabstat hd if hf_involved == 1 [aw=hf_intensity_pre], by(day_type) stat(mean p50 n)

* 6.2 type premium with the book held constant
foreach v in hfd_large hfS_large hfd_policy hfS_policy hfd_dir hfS_dir {
    capture drop `v'
}
gen double hfd_large  = log_hf_intensity * (abs(S) > 1)
gen double hfS_large  = log_hf_intensity * S * (abs(S) > 1)
gen double hfd_policy = log_hf_intensity * policy_day
gen double hfS_policy = log_hf_intensity * S * policy_day
gen double hfd_dir    = log_hf_intensity * hd
gen double hfS_dir    = log_hf_intensity * S * (abs(S) > 1) * hd

* benchmark without directionality (Section 4 spec), then with it:
reghdfe delta_y c.log_hf_intensity hfd_large hfd_policy hfS_large hfS_policy ///
    duration bid_ask_spread ctd_flag, absorb(duration_match isin) ///
    vce(cluster business_date isin)
reghdfe delta_y c.log_hf_intensity hfd_large hfd_policy hfd_dir ///
    hfS_large hfS_policy hfS_dir ///
    duration bid_ask_spread ctd_flag, absorb(duration_match isin) ///
    vce(cluster business_date isin)
test hfS_policy == 0     // premium surviving the book control = content
test hfS_dir == 0        // book channel inside the pooled profile
